// <auto-generated />
namespace WebAPISample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedsomestartercodeintheseedmethodsothatwhenIruntheapplicationtheinformationwillautomaticallybeadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedsomestartercodeintheseedmethodsothatwhenIruntheapplicationtheinformationwillautomaticallybeadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201907241250548_Added some starter code in the seed method so that when I run the application the information will automatically be added."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
